language: ruby
rvm:
 - 2.2
 - 2.3.0
services:
  - postgresql
before_script:
  - psql -c "CREATE USER permadb WITH PASSWORD 'permadb';" -U postgres
  - psql -c 'create database permadb_test;' -U postgres
script: bundle exec rspec spec